[package]
name = "coffee_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.114"
surrealdb = "2.3.10"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "fs"] }
chrono = "0.4.42"